### ISSUE TITLE
Allow specifying custom language syntaxes

### ISSUE THREAD

**Issue by fgelm01** [spirali/nelsie#15]
It seems like you use [`synctet`](https://github.com/trishume/syntect) for syntax highlighting of code. Would it be possible to expose some mechanism to add more syntaxes than the ones that library bundles by default?

**Comment by spirali** [comment]
I have added an implementation. Unfortunately I have found a bug that custom syntaxes does not work when defaults loaded. So you have to disable loading default syntaxes by `Resources(default_code_syntaxes=False)`. Themes are ok. It seems as a bug in upstream crate. I will investigate tomorrow.

**Comment by spirali** [comment]
I have found the source of the problem, so #16 fully solves this issue.

**Comment by fgelm01** [comment]
Thank you!
