### ISSUE TITLE
Text with inline styles disappears from pdf.

### ISSUE THREAD

**Issue by fgelm01** [spirali/nelsie#19]
When using `text`, certain combinations of inline styles and text contents cause the text to not appear in the generated pdf file.

I can't discern a pattern in what strings cause this, but it doesn't happen when `parse_styles=False`.

Here's a minimal example:

```python
import nelsie

deck = nelsie.SlideDeck(width=320, height=240)

@deck.slide()
def _(slide: nelsie.Slide) -> None:
    s = "~monospace{s} specifi"
    slide.text(s, parse_styles=False, bg_color="#fa8080")
    slide.text(s, parse_styles=True, bg_color="#80fa80")

deck.render("repro", "svg")
```

![0-0-1](https://github.com/spirali/nelsie/assets/1566237/322d54f2-2a3d-4b0a-a98a-e16be1df78d8)

The cut-off is expected due to slide deck dimensions being small. But the second line looks very strange in the .svg and doesn't appear at all in the .pdf.

This is using version 0.6.0

**Comment by spirali** [comment]
Thank you for your report. I can reproduce it and I will look at it.

**Comment by fgelm01** [comment]
Thanks for looking at this. I just ran into the bug again with new strings:

```python
slide.text("~code{start} creates a ~code{From} value.")
slide.text("~code{finish} takes a ~code{To} value.")
```

Both lines don't appear in the pdf.

**Comment by spirali** [comment]
My first investigation is that it is a bug in an upstream crate usvg that converts text in to paths. It seems that the bug is already fixed but because of another dependency (svg2pdf) we are still on the buggy version. In next days I will try to investigate how to upgrade without breaking dependencies.

**Comment by spirali** [comment]
I have tested dev version of svg2pdf and it seems to work. The main problem is now that the new version of usvg made substantial changes in API. I have started to work on port of Nelsie to the current version of usvg but it will take some time.

**Comment by spirali** [comment]
Btw: It seems that the text disappears when ligature is created, so a temporary workaround is to use a monospace font that usually does not create ligatures. I know, not a great solution ...
