### ISSUE TITLE
Hyperlink support

### ISSUE THREAD

**Issue by georgik** [spirali/nelsie#21]
Thank you for creating Nelsie. It's very useful and fast.

Please, could you give a hint how to create a hyperlink? 
I was searching the documentation for keyboards like: link, href, hyperlink. 
Could you provide snippet of code with link to https?

**Comment by spirali** [comment]
Unfortunately, links are not supported by the current renderer to PDF. However, I am now working on a custom PDF renderer so it should be possible in the near future.
