### ISSUE TITLE
Allow specifying a default resource directory

### ISSUE THREAD

**Issue by Kobzol** [spirali/nelsie#23]
It would be nice to allow specifying a default directory where e.g. images will be searched (potentially even multiple directories, with a priority, but one should be enough). Essentially the equivalent of the LaTex `\graphicspath{{}}` command. It should help to avoid repeating e.g. `imgs` or `images` in all image paths.

**Comment by spirali** [comment]
It is already implemented: https://spirali.github.io/nelsie/guide/images/#image-directory

**Comment by Kobzol** [comment]
Ah, awesome :star_struck: Sorry, I have to admit that I opened the issue without checking the docs first :man_facepalming:
