### ISSUE TITLE
[Question]: How should I compare Nelsie to Elsie?

### ISSUE THREAD

**Issue by galenseilis** [spirali/nelsie#28]
I notice that there is another package you have created called "Elsie" that seems to have similar goals/scope but with different rendering dependencies.

I happen to like Python and Rust, so either seems good to me... But how should I compare these two packages? What do the use cases look like under one vs the other?

**Comment by spirali** [comment]
Nelsie should fully replace Elsie. If you are missing some features please me know. The only issue I am aware so far is direct Math support. I tried to answer in #29, what possibilities I am now investigating. On the other, math support in Elsie was slightly second-class citizen.
