### ISSUE TITLE
List counting trough multiple pages

### ISSUE THREAD

**Issue by ZakkProjects** [spirali/nelsie#40]
There is (afaik) no way to continue numbered lists across multiple pages.

When using "counters" parameter `q_lst = ListBox(b, list_type="1", counters=[0])` , there is weird behaviour with appending [0] to the end of counters. Which results in counting restart. 
First i thought it has something with nesting lists, but it does not seem to be the case. 

Is there a propper way to continue list on next slide (not show part) ? Or even better, an option to set starting number when using numbered lists ?

**Comment by spirali** [comment]
I am not sure that I understand your problem. If you want split a list on more steps (= pdf pages) then you can use "show" parameter.

```python
    lst = ListBox(slide)
    lst.text("One")
    lst.text(show="2+", text="Two")
    lst.text(show="3+", text="Three")
```

**Comment by ZakkProjects** [comment]
Showing/hiding feature works great.

Problem arises once i try to make a list spanning multiple pages, but hiding all previous content. Quick example:
![image](https://github.com/spirali/nelsie/assets/26041819/83d82782-e57c-4871-9240-fbce2305a68a)

Since boxes reserve their space even if not showed this code:
```
@deck.slide()
def foo(slide):
    b = slide.box(align_items="flex-start", width="100%", p_left="30", p_right="30", p_top="30", p_bottom="80", flex_grow=1, justify_content="start", gap=(10, 10))
    q_lst = ListBox(b, list_type="1")
    q_lst.text("Point 1", show="1")
    lst = q_lst.list()
    lst.text("content 1", show="1")
    lst.text("content 1", show="1")
    lst.text("content 1", show="1")
    lst.text("content 1", show="1")
    lst.text("content 1", show="1")
    lst.text("content 1", show="1")

    q_lst.text("Point 2", show="2")
    lst = q_lst.list()
    lst.text("content 2", show="2")
    lst.text("content 2", show="2")
    lst.text("content 2", show="2")
    lst.text("content 2", show="2")
    lst.text("content 2", show="2")
    lst.text("content 2", show="2")
    lst.text("content 2", show="2")
```
results in lot of empty space and possibly overflowing slide 
![image](https://github.com/spirali/nelsie/assets/26041819/c07cdaef-16be-45ef-8800-b5e7c9bc5b04)

After reading more documentation, i discovered "active" parameter. 
But active parameter on text object inside list does not apply to bullets (similar issue with show which was fixed ??)

which makes this code almost work perfectly:
```
@deck.slide()
def foo(slide):
    b = slide.box(align_items="flex-start", width="100%", p_left="30", p_right="30", p_top="30", p_bottom="80", flex_grow=1, justify_content="start", gap=(10, 10))
    q_lst = ListBox(b, list_type="1")
    q_lst.text("Point 1", active="1")
    lst = q_lst.list(active="1")
    lst.text("content 1", active="1")
    lst.text("content 1", active="1")
    lst.text("content 1", active="1")
    lst.text("content 1", active="1")
    lst.text("content 1", active="1")
    lst.text("content 1", active="1")

    q_lst.text("Point 2", active="2")
    lst = q_lst.list(active="2")
    lst.text("content 2", active="2")
    lst.text("content 2", active="2")
    lst.text("content 2", active="2")
    lst.text("content 2", active="2")
    lst.text("content 2", active="2")
    lst.text("content 2", active="2")
    lst.text("content 2", active="2")
```
![image](https://github.com/spirali/nelsie/assets/26041819/0ae3096d-ffb5-4fa6-97ec-8ea51be430fa)

So in the end, the solution could be applying similar propagation behavior of show to active.

**Comment by spirali** [comment]
Thank you for the explanation. I did not consider this situation. A hotfix is to modify counters directly:

```python
    list = ListBox(slide, list_type="1")
    list.counters[-1] = 2
    list.text("Hello")
```

It will start the counter on different values. I will think about it and prepare a more elegant solution.
